### ISSUE TITLE
pixel_format: BGR888 seems to be wrong for PI cameras

### ISSUE THREAD

**Issue by fishrockz** [lit-robotics/libcamera-rs#45]
I dont know if this is a issue with libcamera or libcamera-rs but i have found some funny features

when i set the image properties as done in the examples

I get

```
    StreamConfigurationRef {
        pixel_format: BGR888,
        size: Size {
            width: 4608,
            height: 2592,
        },
        stride: 13824,
        frame_size: 35831808,
        buffer_count: 1,
    },
```

but when i pipe the saved image into the rust png lib eg

https://gitlab.com/pointswaves/pi-camera/-/blob/trying/camera-app/crates/pi-camera/src/main.rs?ref_type=heads#L461

I get the correct image.

Note this is a pi v3 camera but i get the same thing for the pi hq camera

![image0_r](https://github.com/user-attachments/assets/ab350492-80d1-457d-b12c-267182961d9d)

when i pic the  `pixel_format: RGB888` the colors are mixed up

I wonder if:
  1. the const is wrong
  2. the definition of RGB is some how differnt between the libs..
  3. something else?

I am using the debug output to get the number for fourcc
https://gitlab.com/pointswaves/pi-camera/-/blob/trying/camera-app/crates/pi-camera/src/main.rs?ref_type=heads#L56

for the https://github.com/lit-robotics/libcamera-rs/blob/main/libcamera/examples/jpeg_capture.rs#L15 approche, how does one work out what the letters should be?

CC @kbingham incase you know if this is a libcamera issue?

this is using the 0.3.2 tag of libcamera and main of this repo. ( 2e8303a9b2553c973367875d8ee2bd3a79d5f5d1 )

**Comment by kbingham** [comment]
Different libraries/systems define the pixel formats differently yes. 

V4l2 ARGB == DRM BGRA

so yes it can be very confusing and ultimately needs to be handled correctly in each layer translation. 


Libcamera use the DRM formats

https://github.com/afrantzis/pixel-format-guide can help map between different (same) formats on different integrations
